import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-mining-royalty-settlement-reconciliation",
  "engine": "recovery",
  "title": "Mining Royalty Settlement Reconciliation",
  "shortTitle": "Mining Royalty Settlement Reconciliation",
  "tagline": "Calculate mineral royalties from production, grade, recovery, sales value, and allowable deductions.",
  "industry": "Mining Revenue Assurance",
  "buyer": "Mineral owners, governments, and mining companies",
  "uiPort": 4712,
  "apiPort": 5712,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Mining Royalty Settlement Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments in one accountable workflow. Calculate mineral royalties from production, grade, recovery, sales value, and allowable deductions.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Mining Royalty Settlement Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("mineral-lease-library","MRS01","Mineral lease library","Execute mineral lease library using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed mineral lease library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Mineral lease library Reference","text","MRS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("mine-production-ingestion","MRS02","Mine production ingestion","Execute mine production ingestion using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed mine production ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Mine production ingestion Reference","text","MRS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("assay-grade-validation","MRS03","Assay grade validation","Execute assay grade validation using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed assay grade validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Assay grade validation Reference","text","MRS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("metallurgical-recovery","MRS04","Metallurgical recovery","Execute metallurgical recovery using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed metallurgical recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Metallurgical recovery Reference","text","MRS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("payable-metal-calculation","MRS05","Payable metal calculation","Execute payable metal calculation using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed payable metal calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Payable metal calculation Reference","text","MRS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("benchmark-price-mapping","MRS06","Benchmark price mapping","Execute benchmark price mapping using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed benchmark price mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Benchmark price mapping Reference","text","MRS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("sales-revenue-reconciliation","MRS07","Sales revenue reconciliation","Execute sales revenue reconciliation using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed sales revenue reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Sales revenue reconciliation Reference","text","MRS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("treatment-charge-validation","MRS08","Treatment charge validation","Execute treatment charge validation using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed treatment charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Treatment charge validation Reference","text","MRS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("refining-charge-validation","MRS09","Refining charge validation","Execute refining charge validation using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed refining charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Refining charge validation Reference","text","MRS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("transportation-deduction","MRS10","Transportation deduction","Execute transportation deduction using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed transportation deduction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Transportation deduction Reference","text","MRS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("royalty-rate-calculation","MRS11","Royalty rate calculation","Execute royalty rate calculation using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed royalty rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Royalty rate calculation Reference","text","MRS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("settlement-statement-audit","MRS12","Settlement statement audit","Execute settlement statement audit using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed settlement statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Settlement statement audit Reference","text","MRS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("operator-dispute-workflow","MRS13","Operator dispute workflow","Execute operator dispute workflow using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed operator dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Operator dispute workflow Reference","text","MRS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("cash-reconciliation","MRS14","Cash reconciliation","Execute cash reconciliation using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Cash reconciliation Reference","text","MRS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]}),
feature("mine-commodity-analytics","MRS15","Mine commodity analytics","Execute mine commodity analytics using mineral leases, production, assays, recoveries, sales, benchmark prices, treatment charges, transportation, deductions, royalty rates, settlements, and payments.","Produce a governed mine commodity analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Mine / Royalty Agreement","text","Mine / Royalty Agreement · Standard Case"],["caseReference","Mine commodity analytics Reference","text","MRS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1456250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1762063],["domainDriver","Royalty Basis","select","Gross revenue",["Gross revenue","Net smelter return","Production unit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Mineral lease library case","Mine production ingestion case","Assay grade validation case","Metallurgical recovery case","Payable metal calculation case"]})
]);
